# --------------------------------License Notice----------------------------------
# Roster - A member and community management web application for CieFa-ArmA
# Copyright (C) 2018 Mickaël 'lastmikoi' FALCK <lastmikoi@lastmikoi.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# --------------------------------License Notice----------------------------------

language: python
python:
  - "3.6"
install:
  - "pip install tox-travis"
  - "pip install python-coveralls"
script:
  - "tox"  # Will run with the travis-defined python environment
  - "tox -e coverage,safety"
after_success:
  - "coveralls"
